server:
  port: 8888
  #session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /myOlder

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/older?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username : root
    password : 41536141.zjh
    #type: com.alibaba.druid.pool.DruidDataSource
    driverClassName : com.mysql.cj.jdbc.Driver
#  jpa:
#    database : MYSQL
#    show-sql : true
#    hibernate:
#      ddl-auto : update
#      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect : org.hibernate.dialect.MySQL5Dialect

#---
##开发环境配置
#spring:
#  profiles: dev
#server:
#  port: 8888
#  spring:
#  profiles:   #激活开发环境
#    active: dev
#---
##生产环境配置
#spring:
#  profiles: pro
#server:
#  port: 8082